# Support PTV-TRMNL Development
# These links will appear on the GitHub repository page

# GitHub Sponsors
github: angusbergman17-cpu

# Buy Me a Coffee
buy_me_a_coffee: angusbergman

# Other platforms (uncomment and add if applicable)
# ko_fi: angusbergman
# patreon: angusbergman
# custom: ["https://your-donation-link.com"]
