#!/bin/sh
#
# Commute Compute Configuration Helper
# Copyright (c) 2026 Angus Bergman - CC BY-NC 4.0
#

SCRIPT_DIR="$(dirname "$0")"
CONFIG_FILE="$SCRIPT_DIR/config.sh"

echo "=== Commute Compute Configuration ==="
echo ""

# Check if config exists
if [ -f "$CONFIG_FILE" ]; then
    echo "Current configuration:"
    echo "----------------------"
    cat "$CONFIG_FILE"
    echo ""
    echo "To modify, edit: $CONFIG_FILE"
else
    echo "No configuration found."
    echo ""
    echo "Creating default config.sh..."
    
    cat > "$CONFIG_FILE" << 'EOF'
#!/bin/sh
# Commute Compute Configuration
# Copyright (c) 2026 Angus Bergman - CC BY-NC 4.0
#
# Edit this file to configure your Commute Compute display.
#
# REQUIRED: Set your server URL or webhook URL
# Get your webhook URL from the setup wizard at:
#   https://your-server.vercel.app/setup-wizard.html

# Option 1: BYOS Webhook URL (recommended)
# This URL contains your personal config and is generated by the setup wizard.
# export CC_WEBHOOK_URL="https://your-server.vercel.app/api/device/eyJ..."

# Option 2: Direct server URL (requires server-side configuration)
export CC_SERVER="https://your-server.vercel.app"

# Refresh interval in seconds (default: 60)
export CC_REFRESH=60

# Full refresh interval (every N updates, default: 15)
# Full refresh clears e-ink ghosting but takes longer
export CC_FULL_REFRESH_INTERVAL=15

# HTTP timeout in seconds (default: 30)
export CC_HTTP_TIMEOUT=30

# Debug mode (set to 1 for verbose logging)
export CC_DEBUG=0
EOF
    
    echo "Created: $CONFIG_FILE"
    echo ""
    echo "Please edit this file to add your webhook URL."
fi

echo ""
echo "=== Setup Instructions ==="
echo ""
echo "1. Go to: https://your-server.vercel.app/setup-wizard.html"
echo "2. Complete the setup wizard"
echo "3. Copy your webhook URL"
echo "4. Edit $CONFIG_FILE"
echo "5. Set CC_WEBHOOK_URL to your webhook URL"
echo "6. Start the dashboard: ./commute-compute-launcher.sh start"
